### ISSUE TITLE
Newtonsoft.Json dependency version should be lowest supported, not latest available

### ISSUE THREAD

**Issue by kostrse** [manuc66/JsonSubTypes#101]
JsonSubTypes, as a library, should have dependency on Newtonsoft.Json set to minimum supported version, not whatever version is currently latest.

Setting dependency to older version doesn't mean that application will run with outdated version of Newtonsoft.Json, it just means constraint which should be met during version resolution..

It would give users flexibility of choice.

For example, if JsonSubTypes used in another library, which doesn't have explicit requirement on version of Newtonsoft.Json, but since JsonSubTypes enforces latest version, that library has to enforce it too.

Related: #41

**Comment by manuc66** [comment]
Hi,

The current version `1.7.0` depend on `Newtonsoft.Json` version `12.0.3` its code can compile from including version `10.0.1` . The tests need at least version `12.0.1` for (#80): https://github.com/manuc66/JsonSubTypes/blob/15a96d3dadf212faaa29a068a5d3d2b0c850ec74/JsonSubTypes.Tests/NamingStrategyTests.cs#L52

A bugfix release can be envisioned to lower the dependency down to `10.0.1`.

**Comment by kostrse** [comment]
Thanks!. The test project is an example of host application in this case which can perfectly reference a later version of Newtonsoft.Json package than JsonSubTypes does.

**Comment by manuc66** [comment]
Published with version 1.9.0
