### ISSUE TITLE
Question: Root Property Name = Kind?

### ISSUE THREAD

**Issue by imukai** [manuc66/JsonSubTypes#104]
I'm working with a third party trying to manipulate some of their output.  I came across this project which looks very promising but I'm not sure it would handle this one.

Here's a watered down translation of what I am looking at.

Given the following contrived classes:

```cs
public abstract class FruitBase {
    ...some abstract methods
}

public abstract class FruitContainer: FruitBase { 
    public abstract List<FruitBase> Contents;
    public FruitContainer() { Contents = new List<FruitBase>(); }
}

public class Bucket : FruitContainer {
   ...special bucket things
}

public class Apple : FruitBase {
    public int Size;
    public string Color;
}

public class Banana : FruitBase {
  public string Shape;
}
```

Given the following contrived object has been created:

```cs
var bucket = new Bucket();
bucket.Contents.Add(new Apple {Size = 3, Color = "Red"}};
bucket.Contents.Add(new Banana { Shape = "Straight"});
bucket.Contents.Add(new Bucket());
```

And given the following contrived JSON has been produced from said object:

```js
{
   Bucket: { 
      Contents: [
          {  Apple: { Size: 3, Color: "Red"} },
          {  Banana:  { Shape: "Straight" } },
          {  Bucket:  { Contents: [ ] }
      ]
   } 
}
```

Can this library reverse that JSON back into that object?  Everything in that library derives from a common base, including the containers.

In the JSON, note that the property names themselves = the object type represented, except when they are themselves properties (e.g. Contents).

I was about to set out writing my own converter but if yours can handle this, all the better and you get many kudos.  :)

**Comment by manuc66** [comment]
I'm sorry but this library can't map the provided json with the class defined.
