### ISSUE TITLE
Specifying the discriminator using an attribute instead of a property

### ISSUE THREAD

**Issue by mjamro** [manuc66/JsonSubTypes#109]
Right now the library works by using a discriminator property

```
[JsonConverter(typeof(JsonSubtypes), "Type")]
public interface IComponent
{
    string Type { get; }
}

public class FooComponent : IComponent
{
    public string Type => "foo"
}

```

this pollutes the model class with a technical, serialization-related property.

If we could use an attribute instead for the discriminator the model would not require additional properties:

```
[JsonConverter(typeof(JsonSubtypesByAttribute))]
public interface IComponent
{
}

[JsonSubtypeDiscriminator("foo")]
public class FooComponent : IComponent
{
}

```

**Comment by manuc66** [comment]
Hi @mjamro 

What about : https://github.com/manuc66/JsonSubTypes#serializeobject-and-deserializeobject-with-custom-type-property-only-present-in-json ?

**Comment by mehmetkaradeniz** [comment]
@mjamro, It might work scanning the types which has your JsonSubtypeDiscriminator attribute and registering them via the method @manuc66 provided in the comment.
