### ISSUE TITLE
Nuget packages doesn't work for .Net Framework projects

### ISSUE THREAD

**Issue by camhart** [manuc66/JsonSubTypes#11]
This is NOT a bug with JsonSubTypes.  However I think it's worth while to point this out for others attempting to use it.

You'll end up hitting this bug: https://github.com/dotnet/standard/issues/481

**Comment by manuc66** [comment]
I made some changes in the packaging, could you try downloading `https://ci.appveyor.com/api/buildjobs/6qqwhfyp3voq7pn6/artifacts/JsonSubTypes%2Fbin%2FRelease%2FJsonSubTypes.1.1.1.nupkg` and try with:
````cmd
Install-Package c:\download\folder\path\to\JsonSubTypes.1.1.1.nupkg
````

Thanks

**Comment by camhart** [comment]
Appears to work 👍
