### ISSUE TITLE
JsonSubtypesConverterBuilder convert a string value "2010-09-19T03:10:01.777Z" to "09/19/2010 03:10:01"

### ISSUE THREAD

**Issue by Lianliany** [manuc66/JsonSubTypes#116]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
   public class AAAA
    {
        [JsonProperty("type")]
        public string QueryType => GetType().Name;
        public static JsonConverter GetJsonConverter => JsonSubtypesConverterBuilder.Of(typeof(BaseQueryDefinition), "type").Build();
    }

    public class DDDD: AAAA
    {
        public string Field { get; set; }
        public string GreaterThan { get; set; }
        public string LessThan { get; set; }
    }

           var range = new DDDD
            {
                Field = "@timestamp",
                GreaterThan = "2010-09-19T03:10:01.777Z",
                LessThan = "2020-09-19T03:10:01.777Z"
            };
            var settings1 = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            };
            settings1.Converters.Add(AAAA.GetJsonConverter);
            var str2 = JsonConvert.SerializeObject(range);
            var deserialized2 = JsonConvert.DeserializeObject<DDDD>(str2, settings1);
```

### Source/destination JSON

```javascript
{"message":"Place your serialized or deserialized JSON here"}

```

### Expected behavior
str2: "{\"field\":\"@timestamp\",\"greaterThan \":\"2010-09-19T03:10:01.777Z\",\"lessThan \":\"2020-09-19T03:10:01.777Z\"}"
deserialized2  ：{ Field ： "@timestamp", GreaterThan ： "2010-09-19T03:10:01.777Z",LessThan ： "2020-09-19T03:10:01.777Z"}

### Actual behavior
str2: "{\"field\":\"@timestamp\",\"greaterThan \":\"2010-09-19T03:10:01.777Z\",\"lessThan \":\"2020-09-19T03:10:01.777Z\"}"
【str2 is expected】

deserialized2  ：{ Field ： "@timestamp", GreaterThan ： "09/19/2010 03:10:01",LessThan ： "09/19/2020 03:10:01"}
【but deserialized2 is not expected，why are “GreaterThan” and “LessThan” converted to these. I hope them to keep origin "2010-09-19T03:10:01.777Z" and "2020-09-19T03:10:01.777Z"】

### Steps to reproduce

```csharp
// Your calls to here
```

**Comment by manuc66** [comment]
Hi @Lianliany 

It seems you're missing a call to `.RegisterSubtype<DDDD>("DDDD")` see: https://github.com/manuc66/JsonSubTypes#user-content-registration

**Comment by Lianliany** [comment]
Thank you very much! Your answer let me found that this bug was caused by the Nuget Package "JsonSubTypes". The origin version of  "JsonSubTypes" is "1.7.0". Update its version to "1.8.0", then the string can be origin.
