### ISSUE TITLE
Misleading error message on deserialization when subtype is unknown

### ISSUE THREAD

**Issue by MartinHaeusler** [manuc66/JsonSubTypes#125]
### Source/destination types

```csharp
[JsonConverter(typeof(JsonSubtypes), "type")]
[JsonSubtypes.KnownSubType(typeof(Farm), "Farm")]
[JsonSubtypes.KnownSubType(typeof(Office), "Office")]
public abstract class Building {
  public string name { get; set; }    
}

public class Office : Building {}

public class Farm: Building {}
```

### Source/destination JSON

```javascript
{
    "type": "Airport",
    "name": "London Heathrow"
}
```

### Expected behavior

I expected the error message to indicate that there is no registered subtype for string "Airport".

(Background: I've been scratching my head over this for more than an hour now until I realized that the problem was not in my mapping but in the JSON body, which contained a typo in a `type` field...)

### Actual behavior

The exception claims that the type `Building` cannot be instantiated due to being `abstract`:

```
Newtonsoft.Json.JsonSerializationException : Could not create an instance of type Building. Type is an interface or abstract class and cannot be instantiated. Path 'name'
```

### Steps to reproduce

```csharp
JsonConvert.DeserializeObject<Building>(exampleJsonFromAbove);
```

**Comment by manuc66** [comment]
This exception is thown by Newtonsoft.Json, and is more general because it could also be thrown if a registered subtype has been found but is an abstract class or an interface.
