### ISSUE TITLE
New Major to depend on newer JSON

### ISSUE THREAD

**Issue by viceice** [manuc66/JsonSubTypes#131]
**Is your feature request related to a problem? Please describe.**
Currently this lin depends on Json v10 and our Project depends on Json v12.
The problem is we need assembly signing and can't use binding redirects.
Our assemblies need to be deployed to the windows GAC.

**Describe the solution you'd like**
Release new major version which depends on Json v12 ( and v13 in a future release)

**Describe alternatives you've considered**
Fork this project or hook into assembly resoving / loading

**Additional context**
See Problem

*** Source/destination types

```csharp
// not relevant
```

*** Source/destination JSON

```javascript
{"message":"not relevant"}
```

**Comment by manuc66** [comment]
It conflicts with:
- Newtonsoft.Json dependency version should be lowest supported, not latest available #101
- Lower Newtonsoft.Json Support to 9.0.1 #41

**Comment by viceice** [comment]
I know, please do a major version bump when you change the `JSON` dep major version again, so the update doesn't silently pass through.

We use [renovate](/renovatebot/renovate) to manage dependencies with partial automerge and automatic tests can't capture those binding issues 😕

**Comment by manuc66** [comment]
Will be the case once this will be released : https://github.com/manuc66/JsonSubTypes/pull/137
