### ISSUE TITLE
JsonSubtypesConverterBuilder SetFallbackSubtype

### ISSUE THREAD

**Issue by BarnabyDove** [manuc66/JsonSubTypes#147]
I noticed that the generic method `SetFallbackSubtype<T>(object value)` on `JsonSubtypesConverterBuilder` requires an object parameter. It wasn't immediately apparent why, since `SetFallbackSubtype(Type fallbackSubtype)` does not.

Looking at the code, I can see that `SetFallbackSubtype<T>(object value)` is actually just calling `RegisterSubtype(typeof(T), value);` internally:

```
        public JsonSubtypesConverterBuilder SetFallbackSubtype<T>(object value)
        {
            return RegisterSubtype(typeof(T), value);
        }
```

This looks to be a mistake. Instead, I think this should not require an object parameter, and instead call `SetFallbackSubtype(Type fallbackSubtype)` internally:

```
        public JsonSubtypesConverterBuilder SetFallbackSubtype<T>()
        {
            return SetFallbackSubtype(typeof(T));
        }
```

Obvioously, the easy workaround is to use `SetFallbackSubtype<T>(object value)` instead.

If the above is correct, I am happy to submit a PR for the fix.

Thanks.

**Comment by manuc66** [comment]
Hello,

I also think that's a mistake, and unfortunately there were no tests introduced for that method 

I would be happy to integrate your PR :)
