### ISSUE TITLE
Wrong assembly on Nuget?

### ISSUE THREAD

**Issue by fgather** [manuc66/JsonSubTypes#15]
Hi,

I tested the new and very cool "custom enum" - feature and noticed that the assembly published on Nuget seems to be an older version of JsonSubTypes. When I build it from source it works fine.

**Comment by manuc66** [comment]
Hi,

@fgather could you confirm that you're using the [version 1.1.1](https://www.nuget.org/packages/JsonSubTypes/1.1.1) ?

I checked the ``jsonsubtypes.1.1.1.nupkg\lib\net47\jsonsubtypes.1.1.1.nupkg\lib\net47\`` with [ILSpy](http://ilspy.net/) and it is not an older version and does contains the changes that are on the develop branch.

**Comment by fgather** [comment]
Hi, I checked it with a manual download, too and it seems to be in there. However, in my project nuget says 1.1.1 . So I removed everything, cleared the cache and its fine now. When does humanity achieve good dependency management? 
Thx, for the check!
