### ISSUE TITLE
JsonReaderException does not contain a constructor that takes 5 arguments

### ISSUE THREAD

**Issue by tpaslou** [manuc66/JsonSubTypes#154]
Hi 

I have just downloaded the code and imported it to my Unity project. The only compile error that appears is :

Assets\JsonSubTypes\JsonSubtypes.cs(174,24): error CS1729: 'JsonReaderException' does not contain a constructor that takes 5 arguments

**Comment by manuc66** [comment]
Hi @tpaslou 

On which version of Newtonsoft.Json are you depending on ?

**Comment by tpaslou** [comment]
The unity package is based on n Json .Net Version: 8.0.3

**Comment by tpaslou** [comment]
> Hi @tpaslou
> 
> On which version of Newtonsoft.Json are you depending on ?

The unity package is based on n Json .Net Version: 8.0.3

**Comment by manuc66** [comment]
@tpaslou 

Either upgrade to the latest version of Newtonsoft.Json or use that constructor `return new JsonReaderException(message);`

If you upgrade Newtonsoft.Json, the recommended way to consume this library is by using the nuget package

Best regards

**Comment by tpaslou** [comment]
> @tpaslou
> 
> Either upgrade to the latest version of Newtonsoft.Json or use that constructor `return new JsonReaderException(message);`
> 
> If you upgrade Newtonsoft.Json, the recommended way to consume this library is by using the nuget package
> 
> Best regards

Thank you for your help !
