### ISSUE TITLE
Persistent settings

### ISSUE THREAD

**Issue by tpaslou** [manuc66/JsonSubTypes#156]
Hi

I am trying to deserialize my Json. So lets say that there is a json file with many different registered subtypes. How can I deserialize it ? In the example it shows how to deserialize only after already registering the subtype. Is there a way to keep the settings between different sessions ? Or there is another way ?

**Comment by manuc66** [comment]
Hi @tpaslou 
 
Which example are you using ?

If you use attribute base configuration, they are defined a compilation time to they remain "between different sessions"
If you are using the ConverterBuilders they create converters to ba addted on Setting's Converters, so if you reause the setting between session, your configuration will remain "between different sessions"
