### ISSUE TITLE
Support for both camel case and non camel case parameters

### ISSUE THREAD

**Issue by camhart** [manuc66/JsonSubTypes#31]
Here's my current setup:

  ```
  [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(A), PriceDiscountType.A)]
    [JsonSubtypes.KnownSubType(typeof(B), PriceDiscountType.B)]
    [JsonSubtypes.KnownSubType(typeof(C), PriceDiscountType.C)]
    [JsonSubtypes.KnownSubType(typeof(D), PriceDiscountType.D)]
    [JsonSubtypes.KnownSubType(typeof(E), PriceDiscountType.E)]
    [JsonSubtypes.KnownSubType(typeof(F), PriceDiscountType.F)]
    [JsonSubtypes.KnownSubType(typeof(G), PriceDiscountType.G)]
    public abstract class PriceDiscount : Core.Toolkit.ICloneable
```

However, at times the default serialization is to use camel case.  Is there a way to make this work for both camel case, and non camel case, so that I don't have to worry about which is being used?

**Comment by manuc66** [comment]
Hi,

You can tweak the way PriceDiscountType is serialized with Newtonsoft.Json, JsonSubtypes match serialization of `PriceDiscountType.X` with the value found  in the incoming JSON.

**Comment by Hauptsatana** [comment]
@manuc66 Thank you for such an awesome library!
Could you please give more details and maybe example for your previous comment?

I had similar issue with case of property names. Here is my current working setup:
```
[JsonConverter(typeof(JsonSubtypes), "type")]
[JsonSubtypes.KnownSubType(typeof(FleetInput), "fleet")]
[JsonSubtypes.KnownSubType(typeof(CampInput), "camp")]
public abstract class AbstractOrganizationUnitInput
```

As @camhart I have "Type" property in C# class, and firstly used `[JsonConverter(typeof(JsonSubtypes), "Type")]` but exception was thrown during deserialization as my JsonSerializer uses camelCase.
When I changed name to "type", everything got normal.

Could you please explicilty state in documentation that we should use JSON object property name, not the class one? Is it possible to make you converter be aware of JsonSerializer settings to use C# class property name?

**Comment by manuc66** [comment]
Hi @Hauptsatana, @camhart 

I had read a bit too rapidly the original question (sorry), I thought it was about about the case of the enum. So here is what I thought about... :
```csharp
[JsonConverter(typeof(StringEnumConverter), true)]
public enum PriceDiscountType
{
    A,
    B
}
```
--
I confirm that the discriminator property name is the one from the JSON object so that this sample test succeed:

```csharp
[JsonConverter(typeof(JsonSubtypes), "kind")]
public interface IAnimal
{
	[JsonProperty("kind")]
	string Type { get; }
}

public class Dog : IAnimal
{
	public string Type { get; } = "Dog";
	public string Breed { get; set; }
}

[Test]
public void Demo()
{
	var animal =
		JsonConvert.DeserializeObject<IAnimal>(
			"{\"kind\":\"Dog\",\"Breed\":\"Jack Russell Terrier\"}");
	Assert.AreEqual("Jack Russell Terrier", (animal as Dog)?.Breed);
	Assert.AreEqual("Dog", animal.Type);
}
```

As for now there is no know workaround to match `typeMappingPropertyName` with a JSON property name that does not have the same case.

For the documentation concern, as a consumer of this library, where in the documentation would you have expected to find this ? (And feel free to submit a PR ;-))

**Comment by manuc66** [comment]
Support for different case is released with v1.4.0 and documentation has been updated

**Comment by camhart** [comment]
Is this enabled by default?  Or is there some magic way to turn it on?

Thanks btw!

**Comment by manuc66** [comment]
@camhart It's enabled by default and
- should have the same property matching behavior than JSON.NET 
- shouldn't need `JsonProperty` attribute.

**Comment by jbetances** [comment]
I am trying to implement a similar feature.
[JsonConverter(typeof(JsonSubtypes), "SearchType")]
[JsonSubtypes.KnownSubType(typeof(CountrySearchDto), "country")]
[JsonSubtypes.KnownSubType(typeof(StateSearchDto), "state")]
public class SearchDto{
    public string SearchType{get; set;}
}

public class CountrySearchDto : SearchDto{
}
public class StateSearchDto : SearchDto{
}

    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "SearchType")]
    [JsonInheritanceAttribute("CountrySearchDto", typeof(CountrySearchDto))]
    [JsonInheritanceAttribute("SearchSearchDto", typeof(StateSearchDto))]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.18.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class SearchDto
    {
        [Newtonsoft.Json.JsonProperty("searchType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SearchType { get; set; }

        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }

        public static SearchDto FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<SearchDto>(data);
        }
    }

When I execute the generated code, it serializes the object to something like this:
{
"SearchType":"CountrySearchDto",
"searchType":"Country"
}
It always inserts the discriminator.  This json is successfully sent to the webapi but when it attempts to deserialize, it looks for "SearchType" and it doesn't find it.  The code then throws an error.
Any help would be greatly appreciated.
