### ISSUE TITLE
JsonConverter doesn't respect naming rules

### ISSUE THREAD

**Issue by Pzixel** [manuc66/JsonSubTypes#38]
Code sample
```cs
public class DtoTest
{
	[Fact]
	public void FooParsing()
	{
		CheckDeserialization<Foo>("{\"msgType\":\"1\"}");
	}

	private static void CheckDeserialization<T>(string json) where T : class 
	{
		var result = JsonConvert.DeserializeObject<DtoBase>(json);
		Assert.IsType<T>(result);
	}
}

[JsonConverter(typeof(JsonSubtypes), nameof(DtoBase.MsgType))]
[JsonSubtypes.KnownSubType(typeof(Foo), 1)]
public abstract class DtoBase
{
	public virtual int MsgType { get; }
}

class Foo : DtoBase
{
	public override int MsgType { get; } = 1;
}
```

### Expected behaviour

Test passed

### Actual behaviour

> Newtonsoft.Json.JsonSerializationException : Could not create an instance of type Sample.Test.DtoBase. Type is an interface or abstract class and cannot be instantiated. Path 'msgType', line 1, position 11.
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at JsonSubTypes.JsonSubtypes.ThreadStaticReadObject(JsonReader reader, JsonSerializer serializer, JToken jToken, Type targetType)
>    at JsonSubTypes.JsonSubtypes.ReadJson(JsonReader reader, Type objectType, JsonSerializer serializer)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at Sample.Test.DtoTest.CheckDeserialization[T](String json) in C:\Users\Alex\Documents\Repo\SampleEthereum\Sample.Test\UnitTest1.cs:line 17
>    at Sample.Test.DtoTest.FooParsing() in C:\Users\Alex\Documents\Repo\SampleEthereum\Sample.Test\UnitTest1.cs:line 12

---

Test passes for `[JsonConverter(typeof(JsonSubtypes), "msgType")]` attribute value. camelCase is hardcoded somewhere.

**Comment by manuc66** [comment]
Hi, 

looking at the code it seems that your issue is the same as #31 since you use the `nameof` opperator: `nameof(DtoBase.MsgType)` which output "MsgType" where `JsonSubtypes` expect the json property name which is `msgType`.

**Comment by Pzixel** [comment]
@manuc66 Yes. I see it. However, `JsonSerializerSetting` is instructed in (de)-/Serializing in PascalCase. Original `JsonSerializer` respects this setting and treat `msgType` as `MsgType` before mapping it to the property. I believe library extension (like this one) should behave the same way the main library does.

**Comment by Pzixel** [comment]
E.g. input data can be:
```cs
const string json = "[{\"msgType\":\"1\"}, {\"MsgType\":\"1\"}]"
var a = JsonConvert.DeserializeObject<Foo>(json);
var b = JsonConvert.DeserializeObject<DtoBase>(json);
```

The former works fine, the latter throws an exception. It looks like an undesirable behavior.

**Comment by manuc66** [comment]
@Pzixel by default this works:

```csharp
var serializeObject = JsonConvert.SerializeObject(new Foo());
CheckDeserialization<Foo>(serializeObject);
```

How do you instruct PascalCase, is it by defining `ContractResolver` ? 

This test fails and I agree, that it looks like an undesirable behavior:
```csharp
var settings = new JsonSerializerSettings();
JsonConvert.DefaultSettings = () => settings;
settings.ContractResolver = new CamelCasePropertyNamesContractResolver();

var serializeObject = JsonConvert.SerializeObject(new Foo());
CheckDeserialization<Foo>(serializeObject);
```

**Comment by manuc66** [comment]
This is due to this: https://github.com/JamesNK/Newtonsoft.Json/blob/e1dfefe00b77b82e844771c1ad3d66fa94f8c057/Src/Newtonsoft.Json/Serialization/JsonPropertyCollection.cs#L132 :

```
        /// <summary>
        /// Gets the closest matching <see cref="JsonProperty"/> object.
        /// First attempts to get an exact case match of <paramref name="propertyName"/> and then
        /// a case insensitive match.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <returns>A matching property if found.</returns>
        public JsonProperty GetClosestMatchProperty(string propertyName)
        {
            JsonProperty property = GetProperty(propertyName, StringComparison.Ordinal);
            if (property == null)
            {
                property = GetProperty(propertyName, StringComparison.OrdinalIgnoreCase);
            }

            return property;
}
```

**Comment by manuc66** [comment]
Thanks for pinpointing the unexpected behaviour discrepency with Newtonsoft.Json !

If you could review the PR, I'll then be able to publish it in 1.4.0 in the next 48h (I hope).

**Comment by Pzixel** [comment]
@manuc66 look great. I have only single suggestion, see PR.
