### ISSUE TITLE
Lower Newtonsoft.Json Support to 9.0.1

### ISSUE THREAD

**Issue by camhart** [manuc66/JsonSubTypes#41]
It doesn't appear that newtonsoft 10.0.3 is required currently.  Any chance we could have JsonSubTypes change that dependency to 9.0.1?

In an effort to help, I made the change: 
https://github.com/manuc66/JsonSubTypes/pull/40

The tests all passed on my local machine, however it looks like the CICD failed.

**Comment by manuc66** [comment]
Hi @camhart ,

Could you explain why you think lowering `Json.NET` to `9.0.1` is a better strategy compared to 

- status

- upgrading to the current latest version `11.0.2` ?

Thanks

**Comment by camhart** [comment]
If JsonSubTypes has a dependency on Json.NET 11.0.2, then any project consuming JsonSubTypes now has to use Json.NET 11.0.2 as well.  If it's dependency is on Json.NET 9.0.1, wouldn't that mean people could use 9.0.1, 10.0.3, or 11.0.2?

I'm stuck using Json.NET 9.0.1 because Azure functions are stuck on 9.0.1 (for V1 functions--V2 supports other versions but V2 is in beta/preview and is not production ready).

**Comment by manuc66** [comment]
@camhart have you tried something like that : https://codopia.wordpress.com/2017/07/21/how-to-fix-the-assembly-binding-redirect-problem-in-azure-functions/ ?

**Comment by camhart** [comment]
I'll give it a shot.  Thanks for the suggestion!

**Comment by camhart** [comment]
@manuc66 I could get that to work for any serialization/deserialization I did within my own code, but it does NOT work for anything being done by azure.

This means any data bindings (CloudTable, DocumentDB, etc.) doesn't work.  This makes it unusable for me.

If you don't want to merge the PR, I'll just be maintaining the fork at least until we can get to V2 functions.

**Comment by manuc66** [comment]
@camhart I would prefer to target the latest version of Json.NET, I think it's the way it's the most usefull.

Thanks for providing a workaround for those who may have the same issue than you.

**Comment by kostrse** [comment]
Actually, for libarries versions of dependencies do not mean that users of the library have to use old version of dependency, it's just minimum requirement constraint.

So, the proper way is to have minimum possible version of Json.NET with which JsonSubTypes is supported. so users have flexibility of choice.
