### ISSUE TITLE
Bumps Newtonsoft.Json from 10.0.3 to 11.0.2.

### ISSUE THREAD

**Issue by manuc66** [manuc66/JsonSubTypes#47]
Update dependency

**Comment by manuc66** [comment]
@ChrisTorng This project does not leverage new features/API of JSON.NET, however it's valuable to know that it's still working with the latest JSON.NET library.

**Comment by ChrisTorng** [comment]
??? So, can you lower the NuGet dependency to a lower version, like 10.0.3? If I want to use the latest JsonSubTypes 1.5.1, I'm forced to upgrade Newtonsoft.Json to 11.0.2. But I'm not planning to upgrade right now.
