### ISSUE TITLE
Read.me imports into my project with nuget package

### ISSUE THREAD

**Issue by CurlyBraceTT** [manuc66/JsonSubTypes#51]
I believe its not the desirable behavior. I can't even delete it.

![image](https://user-images.githubusercontent.com/8270922/46921771-1aa2e900-d008-11e8-9978-bf9169174da8.png)

**Comment by manuc66** [comment]
Thanks for reporting. Reproduced with  `Rider` as well.

**Comment by manuc66** [comment]
@CurlyBraceTT could you confirm it's fixed for you ?

**Comment by CurlyBraceTT** [comment]
@manuc66 Yep, all good now, thanks!
