### ISSUE TITLE
Discriminant in children?

### ISSUE THREAD

**Issue by Gh0s7** [manuc66/JsonSubTypes#69]
Hi there,
I wanted to use your package but I'm having issues with my use case.

Here's the JSON:

```json
{
    "id": 0,
    "in": [
        {
            "disc": "a"
        },
        {
            "prop": "propr"
        }
    ]
}
```

What I'd like to do is to be able to discriminate based on the `disc` value, which is in the first child of `in` property.

My idea was to have something like that in my base class:

```csharp
[JsonConverter(typeof(JsonSubtypes), nameof(In))]
[JsonSubtypes.KnownSubType(typeof(ChildRequest), "a")]
[JsonSubtypes.KnownSubType(typeof(ChildRequest2), "b")]
public abstract class BaseClass {
    [JsonProperty("in")]
    public In[] In{ get; set; }

    public string Disc => In.First().Disc;
}
```

but it's not working, as Json.Net tries to deserialize it into `BaseClass` (which can't be initialized as it's `abstract`).

Is there a way to do something like that or am I out of luck?

**Comment by manuc66** [comment]
Hi @Gh0s7 

Unfortunately `JsonSubTypes` does not support this use case.

It's very frequent that child class could be [discriminated by the presence of a property](https://manuc66.github.io/JsonSubTypes/#deserializeobject-mapping-by-property-presence), maybe it's something that might help you...
