### ISSUE TITLE
KnownSubType with property value

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [manuc66/JsonSubTypes#74]
**Is your feature request related to a problem? Please describe.**
I am trying to deserialize an array of items which derive from a base class. These items don't have a `$type` property but do have a similar property by a different name, which is set to a constant string per property type. I am able to use `KnownSubTypeWithProperty` to get pretty close but I don't think this solution will continue to work as more subtypes are added.

**Describe the solution you'd like**
An attribute that allows you to specify the type, property name, and property value to look for.
```
[JsonSubtypes.KnownSubTypeWithPropertyValue(typeof(HeaderWidget), "widget_type", "HEADER")]
[JsonSubtypes.KnownSubTypeWithPropertyValue(typeof(EmailWidget), "widget_type", "EMAIL")]
```

**Describe alternatives you've considered**
I am currently using `KnownSubTypeWithProperty` to differentiate between the types but two of my types are identical except for the `widget_type` field. 
`EmailWidget`
```json
    {
      "label": {
        "text": "Email",
        "hint": "Original text: Email"
      },
      "required": true,
      "order": 4,
      "widget_type": "EMAIL"
    }
```
`TextWidget`
```json
    {
      "label": {
        "text": "Comments",
        "hint": "Original text: Comments"
      },
      "order": 3,
      "widget_type": "TEXT"
    }
```
Right now I am differentiating by not having any of the `TextWidget`s that I have specified include the `required` property, but that's not going to work in all cases. I could also make these two types actually be the same class but I think that is a less than ideal solution since all other types have their own class and I'd like to keep it consistent.

**Additional context**

I think this is related to #69 but not quite the same.

*** Source/destination types

This is a subset of the types I have.
```csharp
    [JsonConverter(typeof(JsonSubtypes))]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(HeaderWidget), "text")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(NameWidget), "placeholder_last_name")]
    public abstract class Widget
    {
        [Newtonsoft.Json.JsonProperty("order", Required = Newtonsoft.Json.Required.Always)]
        public int Order { get; set; }

        [Newtonsoft.Json.JsonProperty("widget_type", Required = Newtonsoft.Json.Required.Always)]
        public string WidgetType { get; set; }
    }

    public class HeaderWidget : Widget
    {
        public const string WIDGET_TYPE = "HEADER";

        public HeaderWidget()
        {
            WidgetType = WIDGET_TYPE;
        }

        [Newtonsoft.Json.JsonProperty("text", Required = Newtonsoft.Json.Required.Always)]
        public string Text { get; set; }
    }

    [ExcludeFromCodeCoverage]
    public class NameWidget : Widget
    {
        public const string WIDGET_TYPE = "NAME";

        public NameWidget()
        {
            WidgetType = WIDGET_TYPE;
        }

        [Newtonsoft.Json.JsonProperty("label", Required = Newtonsoft.Json.Required.Always)]
        public WidgetLabel Label { get; set; }

        [Newtonsoft.Json.JsonProperty("placeholder_last_name", Required = Newtonsoft.Json.Required.Always)]
        public string PlaceholderLastName { get; set; }

        [Newtonsoft.Json.JsonProperty("placeholder_first_name", Required = Newtonsoft.Json.Required.Always)]
        public string PlaceholderFirstName { get; set; }
    }
```

*** Source/destination JSON

```javascript
    {
      "text": "Gift amount",
      "order": 0,
      "widget_type": "HEADER"
    },
    {
      "label": {
        "text": "Name",
        "hint": "Original text: Name"
      },
      "placeholder_last_name": "Last name",
      "placeholder_first_name": "First name",
      "order": 3,
      "widget_type": "NAME"
    }
```

**Comment by manuc66** [comment]
Hi @Blackbaud-ChristiSchneider 

It seems that it could be supported by the feature implemented in #60 (not yet released)

**Comment by Blackbaud-ChristiSchneider** [comment]
I took a few minutes to out and it didn't work - I'll see if I can find some time to dig in. I'm not sure if I'm misunderstanding how it is intended to work - should we expect that `$PayloadKind` (or whatever) is included in the json to deserialize?

**Comment by manuc66** [comment]
And why not simply with:

```cs
    [JsonConverter(typeof(JsonSubtypes), "widget_type")]
    [JsonSubtypes.KnownSubType(typeof(HeaderWidget), "HEADER")]
    [JsonSubtypes.KnownSubType(typeof(NameWidget), "NAME")]
    [JsonSubtypes.KnownSubType(typeof(EmailWidget), "EMAIL")]
    public abstract class Widget
    {
        [JsonProperty("order", Required = Required.Always)]
        public int Order { get; set; }

        [JsonProperty("widget_type", Required = Required.Always)]
        public string WidgetType { get; set; }
    }
```

See: https://dotnetfiddle.net/oPgG6n

**Comment by Blackbaud-ChristiSchneider** [comment]
I confirmed this works with 1.6.0, thanks a bunch!
