### ISSUE TITLE
Write support

### ISSUE THREAD

**Issue by acesyde** [manuc66/JsonSubTypes#76]
**Is your feature request related to a problem? Please describe.**
Can you provide mechanism for WriteJson method ?
This library works very well for deserialize but serialization it's not implemented and i need it to store polymorphism in EventStore or MongoDb for a CQRS system

**Describe the solution you'd like**
Use WriteJson method to produce same json as ReadJson

**Additional context**
Polymorphism for fields abstraction in a CMS over CQRS/ES (event store don"t understand inheritance of objects by default)

*** Code
```csharp
    [JsonConverter(typeof(JsonSubtypes), "kind")]
    [JsonSubtypes.KnownSubType(typeof(StringFieldEntity), "string")]
    public abstract class FieldEntity : Entity<FieldId>
    {
        public string Name { get; set; }
        
        protected FieldEntity(FieldId id, string name) : base(id)
        {
            Name = name;
        }
    }
```

*** Source JSON

```javascript
{"kind":"string", "value":"test"}
```

*** Destination JSON

```javascript
{"kind":"string", "value":"test"}
```

**Comment by manuc66** [comment]
Hi @acesyde 

If you look at the tests, by example at https://github.com/manuc66/JsonSubTypes/blob/master/JsonSubTypes.Tests/JsonSubTypesTests.cs#L136 you can see that discriminant field can be serialized but have to declare a property on the type.

If you won't or don't have the possibility to add a discriminant field to your object you can use dynamic registration as shown in the documentation https://manuc66.github.io/JsonSubTypes/#serializeobject-and-deserializeobject-with-custom-type-property-only-present-in-json

**Comment by acesyde** [comment]
Oh Thank you
I think EventFlow (CQRS) doesn't handle converter correctly
