### ISSUE TITLE
Infinite loop when specifying name of abstract base class as discriminator

### ISSUE THREAD

**Issue by kimsey0** [manuc66/JsonSubTypes#82]
### Source/destination types

```csharp
[JsonConverter(typeof(JsonSubTypes.JsonSubtypes), "Discriminator")]
abstract class Base {
	
}

class Derived : Base {
	public string Discriminator => "Derived";
}
```

### Steps to reproduce

```csharp
JsonConvert.DeserializeObject<Base>("{\"Discriminator\":\"Base\"}")
```

### Expected behavior

JsonSubTypes should throw a `JsonSerializationException`.

### Actual behavior

JsonSubTypes goes into an infinite loop and hangs.

**Comment by manuc66** [comment]
Hi @kimsey0 

Thanks a lot for spotting this issue and providing a PR !

The bug was introduced in the latest `1.6.0`
