### ISSUE TITLE
Fallback to JSONPath to allow nested field as a deserialization property.

### ISSUE THREAD

**Issue by remgodow** [manuc66/JsonSubTypes#89]
I'd like to suggest an enhancement to support fallback to JSONPath when looking for property name and/or value.

**Describe the solution you'd like**
An ability to use nested field in json as a discriminator name (ex. data.field) for 
```
[JsonConverter(typeof (JsonSubtypes), "data.field")]
    [JsonSubtypes.KnownSubType(typeof (SomeClass), "value")]

{
   data: {
     field: "value"
   }
}
```
It is useful when creating C# model for given API, which you cannot change.
Fallback to JSONPath requires minimal changes (using JObject.SelectToken(discriminatorName) when it had not been found using existing method).

I have implemented described changes in the library, it passes all unit tests, and I use the change in my project. I'd be glad to do the pull request if you'd accept this enhancement.

**Comment by manuc66** [comment]
Hi @remgodow 

I'm open for such kind of feature, feel free to open a PR

I'm just wondering how it could live with dotted proterty name

Thanks

**Comment by remgodow** [comment]
I've opened the PR.
Tests confirm that it is compatible with dotted property names. 
I believe that thanks to JSONPath it should cover many convoluted models (which is good when there is a need to consume weird model, not that much when allowing for designing such models ;).
