### ISSUE TITLE
Parse string enum values

### ISSUE THREAD

**Issue by szmalec** [manuc66/JsonSubTypes#9]
It would be cool if ConvertJsonValueToType() could also parse enum values which are stored in JSON as string and not only int enum representation... Eg.:
`JsonConvert.DeserializeObject<MainClass>("{\"SubTypeData\":{\"ZzzField\":\"zzz\",\"SubTypeType\":\"WithAaaField\"}}")`

Event better if there would be implemented System.Runtime.Serialization.EnumMember value handling. Eg. for enum:
```
public enum SubType
{
   [System.Runtime.Serialization.EnumMember(Value = "aaaField")]
   WithAaaField,
   WithZzzField
}
```
then in JSON:
`JsonConvert.DeserializeObject<MainClass>("{\"SubTypeData\":{\"ZzzField\":\"zzz\",\"SubTypeType\":\"aaaField\"}}")`

Do you think that it could be implemented?

By the way - JsonSubTypes is great! Thanks.

**Comment by manuc66** [comment]
Hello,

You could achieve it right now with this:
```csharp
            public class MainClass
            {
                public SubTypeClassBase SubTypeData { get; set; }
            }

            [JsonConverter(typeof(JsonSubtypes), "SubTypeType")]
            [JsonSubtypes.KnownSubType(typeof(SubTypeClass1), "aaaField")]
            [JsonSubtypes.KnownSubType(typeof(SubTypeClass2), "zzzField")]
            public class SubTypeClassBase
            {
                public SubType SubTypeType { get; set; }
            }

            [JsonConverter(typeof(StringEnumConverter))]
            public enum SubType
            {
                WithAaaField,
                [System.Runtime.Serialization.EnumMember(Value = "zzzField")]
                WithZzzField
            }
```

```csharp
            [Fact]
            public void Deserialize()
            {
                var obj = JsonConvert.DeserializeObject<MainClass>("{\"SubTypeData\":{\"ZzzField\":\"zzz\",\"SubTypeType\":\"zzzField\"}}");
                Assert.Equal("zzz", (obj.SubTypeData as SubTypeClass2)?.ZzzField);
            }
```

Does it match what you expect ?

**Comment by manuc66** [comment]
I tried to provide a solution to avoid passing strings:

```chsarp
[JsonConverter(typeof(JsonSubtypes), "SubTypeType")]
[JsonSubtypes.KnownSubType(typeof(SubTypeClass1), SubType.WithAaaField)]
[JsonSubtypes.KnownSubType(typeof(SubTypeClass2), SubType.WithZzzField)]
public class SubTypeClassBase
{
    public SubType SubTypeType { get; set; }
}
```

But I'm not satisfied about it because of the additional ``JsonConvert.SerializeObject``.

**Comment by sir-boformer** [comment]
Are you planning to push this to nuget?

**Comment by manuc66** [comment]
@sir-boformer I tried today to find a better way to avoid potential performance decreases and I got something that I'm more comfortable with. Maybe you could look at it and tell me what you think about then I could publish it on nuget...

**Comment by manuc66** [comment]
Shipped into https://www.nuget.org/packages/JsonSubTypes/1.1.0

**Comment by sir-boformer** [comment]
Thank you!
