### ISSUE TITLE
System.NotSupportedException: Deserialization of reference types without parameterless constructor is not supported.

### ISSUE THREAD

**Issue by sanzor** [manuc66/JsonSubTypes#90]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
```
```
[Serializable]
    [JsonConverter(typeof(JsonSubtypes),_type)]
   [JsonSubTypes.JsonSubtypes.KnownSubType(typeof(EventClass.PlayerAction),EventType.PLAYER_ACTION)]
    [JsonSubTypes.JsonSubtypes.KnownSubType(typeof(EventClass.GroupAction), EventType.GROUP_ACTION)]
    public abstract class EventClass {

        public enum EventType {
            PLAYER_ACTION = 0,
            GROUP_ACTION = 1
        }

        private const string _type = "type";

        [JsonProperty(_type)]
        public abstract EventType Discriminator { get;  }
        
    }
    public class GroupAction : EventClass {
            public override EventType Discriminator => EventType.GROUP_ACTION;

            [JsonProperty("eventId")]
            public long EventId { get; set; }
            [JsonProperty("groupId")]
            public long GroupId { get; set; }
        }
 public class PlayerAction : EventClass {
            public override EventType Discriminator =>EventType.PLAYER_ACTION;

            [JsonProperty("eventId")]
            public long EventId { get; set; }
            [JsonProperty("playerId")]
            public long PlayerId { get; set; }
            
        }
```
### Source/destination JSON
```
{
	"class":{
		"type":0,
		"playerId":33,
		"eventId":44
	},
	"data":{
		"action":"finished columbus "
	}
}
```
```javascript
{"message":"Place your serialized or deserialized JSON here"}
```

### Expected behavior

I expect the json to be deserialized to a `PlayerAction` class.

### Actual behavior

> System.NotSupportedException: Deserialization of reference types without parameterless constructor is not supported. Type 'LS.Models.EventClass'
>    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_DeserializeMissingParameterlessConstructor(Type invalidType)
>    at System.Text.Json.JsonSerializer.HandleStartObject(JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
>    at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)
>    at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
>    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
>    at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()

### Steps to reproduce

```csharp
// Your calls to here
`I have tried putting a parameterless constructor in the base class  to no avail.And i have also tried putting parameterless ctors in the derived classes.I still get the same error.

**Comment by manuc66** [comment]
Hi,

I'm sorry but I can't reproduce the problem, see the running sample : https://dotnetfiddle.net/Azbyf4
