### ISSUE TITLE
Usage with JsonSerializer instead of JsonConvert

### ISSUE THREAD

**Issue by KristianVirkus** [manuc66/JsonSubTypes#92]
### Source/destination types

```csharp
	[JsonConverter(typeof(JsonSubtypes), nameof(Kind))]
	[JsonSubtypes.KnownSubType(typeof(ImplementationA1), "a1")]
	[JsonSubtypes.KnownSubType(typeof(ImplementationA2), "a2")]
	public interface IInterfaceA
	{
		string Kind { get; }
		IInterfaceB SubObject { get; set; }
	}

	public class ImplementationA1 : IInterfaceA
	{
		public string Kind { get; set; } = "a1";
		public IInterfaceB SubObject { get; set; }
	}

	public class ImplementationA2 : IInterfaceA
	{
		public string Kind { get; set; } = "a2";
		public IInterfaceB SubObject { get; set; }
	}

	[JsonConverter(typeof(JsonSubtypes), nameof(Kind))]
	[JsonSubtypes.KnownSubType(typeof(ImplementationB1), "b1")]
	[JsonSubtypes.KnownSubType(typeof(ImplementationB2), "b2")]
	public interface IInterfaceB
	{
		string Kind { get; }
		int Value { get; set; }
	}

	public class ImplementationB1 : IInterfaceB
	{
		public string Kind { get; set; } = "b1";
		public int Value { get; set; }
	}

	public class ImplementationB2 : IInterfaceB
	{
		public string Kind { get; set; } = "b2";
		public int Value { get; set; }
	}
```

### Source/destination JSON

None due to serialization/deserialization round-trip for testing purposes:

```csharp
	private static string serialize<T>(T obj) {
		using (var memoryStream = new MemoryStream())
		using (var streamWriter = new StreamWriter(memoryStream))
		using (var jsonTextWriter = new JsonTextWriter(streamWriter))
		{
			var serializer = new JsonSerializer();
			serializer.Serialize(jsonTextWriter, obj);
			return Encoding.UTF8.GetString(memoryStream.ToArray());
		}
	}
```

### Expected behavior

The object `obj` should get converted into a JSON document.

### Actual behavior

The serialization result is always an empty string.

### Steps to reproduce

```csharp
	var obj = new ImplementationA1
	{
		SubObject = new ImplementationB1
		{
			Value = 10,
		},
	};

	Assert.AreNotEqual("", serialize(obj));
```

### More information

Everything just serializes and deserializes fine, if it is done via  the `JsonConvert` class. However large parts of our software directly use the `JsonSerializer` class to serialize and deserialize objects. As now the need for discriminating serialization types arises and we're trying to leverage this library for the task, we're looking for some hint on why `JsonConvert` and `JsonSerializer` works differently with this library and for hopefully some hint on how to get them going together. I've already had a look into the Newtonsoft's source code but without debugging it, I wasn't able to find some crucial differences in serialization handling. Any help or clarification is appreciated.

**Comment by manuc66** [comment]
Hi,

It seems you are at least missing a `textWriter.Flush();` juste before doing ´memoryStream.ToArray()´, that's why you get an empty string

**Comment by KristianVirkus** [comment]
Perfect, that was it. Dunno how I missed that. Thanks a lot.
