### ISSUE TITLE
Please make a release with the latest changes.

### ISSUE THREAD

**Issue by acoats2** [manuc66/JsonSubTypes#97]
Please make a release with the latest changes.  It looks like the current build makes a nuget package that uses the same version that is already published even though the code has changed.

[From AppVeyor Log](https://ci.appveyor.com/project/manuc66/jsonsubtypes/branch/master)
"Collecting artifacts...
Found artifact 'JsonSubTypes\bin\Release\JsonSubTypes.1.6.0.nupkg' matching 'JsonSubTypes\**\*.nupkg' path
Uploading artifacts...
[1/1] JsonSubTypes\bin\Release\JsonSubTypes.1.6.0.nupkg (90,937 bytes)...100%
Deploying using NuGet provider
Publishing JsonSubTypes.1.6.0.nupkg to https://www.nuget.org/api/v2/package...Skipped (A package with ID 'JsonSubTypes' and version '1.6.0' already exists and cannot be modified.)
No packages were pushed.
Build success"

**Comment by manuc66** [comment]
Hi @acoats2 

It's because milestone 1.7.0 is not yet completed : https://github.com/manuc66/JsonSubTypes/milestone/18

**Comment by manuc66** [comment]
Release 1.7.0 published !

**Comment by acoats2** [comment]
Thank you!
